---

- include_tasks: install.yml

- include_tasks: configure.yml

- include_tasks: csr.yml

- include_tasks: sign.yml

- include_tasks: renew.yml

- include_tasks:
    file: revoke.yml
    apply:
      tags: easyrsa-revoke
  tags: easyrsa-revoke

- include_tasks: convert.yml

- include_tasks: download.yml

- include_tasks: dh.yml
